#ifndef EASYCANVASCORE_GLOBAL_H
#define EASYCANVASCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EASYCANVASCORE_LIBRARY)
#  define EASYCANVASCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define EASYCANVASCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EASYCANVASCORE_GLOBAL_H
