#ifndef NDNODEATTRIBUTE_GLOBAL_H
#define NDNODEATTRIBUTE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NDNODEATTRIBUTE_LIBRARY)
#  define NDNODEATTRIBUTESHARED_EXPORT Q_DECL_EXPORT
#else
#  define NDNODEATTRIBUTESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NDNODEATTRIBUTE_GLOBAL_H
